apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-db-config
  namespace: petclinic-ns
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://k8s-eks-db.ctxvni2x7reb.ap-northeast-2.rds.amazonaws.com/petclinic?sslMode=PREFERRED&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"

  # Hikari Pool Settings
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "20"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
  SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "600000"
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "30000"
  SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT: "5000"

