apiVersion: v1
kind: Namespace
metadata:
  name: edge-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-env
  namespace: edge-proxy
data:
  INTERNAL_ALB_DNS: "petclinic-nlb-50aab9fb66c3ba16.elb.ap-northeast-2.amazonaws.com"
  # 아래 3개는 필요할 때만 채우세요 (미사용 시 삭제 또는 빈 값)
  GRAFANA_URL: "http://kps-grafana.monitoring.svc.cluster.local"
  # PROMETHEUS_URL: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
  # LOKI_URL: "http://loki.monitoring.svc.cluster.local:3100"
