apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-proxy
  namespace: edge-proxy
  labels:
    app: petclinic-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic-proxy
  template:
    metadata:
      labels:
        app: petclinic-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: 723926525504.dkr.ecr.ap-northeast-2.amazonaws.com/eks/petclinic-nginx-proxy:v0.6   # ← 빌드/푸시한 이미지 경로
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: proxy-env
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-proxy-svc
  namespace: edge-proxy
spec:
  selector:
    app: petclinic-proxy
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
